version: '3'

services:

  client:
    container_name: client
    build:
      context: ../client
      dockerfile: client.Dockerfile
    ports:
      - "3001:80"
    volumes:
      - /nginx-local:/etc/nginx/conf.d
    depends_on: 
      - node

  node:
    container_name: node
    build:
      context: ../server
      dockerfile: node.Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - /c/Users/vault-volume:/usr/src/app/server/vault-volume
    environment:
      ENV: production
      PORT: 3002
      MYSQL_HOST: db
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    depends_on: 
      - db

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'