kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.app.dbName }}-vc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.app.backendName }}-vc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi