version: '2.1'

services:

  client-master:
    container_name: client-master
    image: rajesh12/angular:master
    ports:
      - "4001:80"
    volumes:
      - /home/rajesh_nitc/nginxdir/master:/etc/nginx/conf.d
    depends_on: 
      - node-master
    networks:
      - master

  node-master:
    container_name: node-master
    image: rajesh12/node:master
    ports:
      - "4002:4002"
    volumes:
      - /home/rajesh_nitc/vault-master:/usr/src/app/server/vault-volume
    environment:
      ENV: production
      PORT: 4002
      MYSQL_HOST: db-master
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    depends_on: 
      - db-master
    networks:
      - master

  db-master:
    container_name: db-master
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - /home/rajesh_nitc/mysql-master-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - master

networks:
  master:
    driver: bridge