version: '2.1'

services:

  client-dev:
    container_name: client-dev
    image: rajesh12/angular:dev
    ports:
      - "3001:80"
    volumes:
      - /home/rajesh_nitc/nginxdir/dev:/etc/nginx/conf.d
    depends_on: 
      - node-dev
    networks:
      - dev

  node-dev:
    container_name: node-dev
    image: rajesh12/node:dev
    ports:
      - "3002:3002"
    volumes:
      - /home/rajesh_nitc/vault-dev:/usr/src/app/server/vault-volume
    environment:
      ENV: production
      PORT: 3002
      MYSQL_HOST: db-dev
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    depends_on: 
      - db-dev
    networks:
      - dev

  db-dev:
    container_name: db-dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/rajesh_nitc/mysql-dev-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - dev

networks:
  dev:
    driver: bridge